preset: laravel
risky: true
finder:
  exclude:
    - node_modules
    - storage
    - vendor
    - tests
  name: '*.php'
  not-name: '*.blade.php'

disabled:
  - length_ordered_imports
enabled:
  - alpha_ordered_imports
